In [8]:
# Step 1:Import Required Libraries

import pandas as pd
import numpy as np

In [9]:
# Step 2: Load Dataset

df = pd.read_csv('PowerBI_Ecommerce_Orders.csv')

In [10]:
# Step 3: Explore the Dataset
# View First 5 Records

df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1001,13-12-2025,Vikas,vikas26@gmail.com,9.796234e+09,Mumbai,Maharashtra,Mouse,Electronics,2.0,499.0,0.0,COD,Delivered,23-12-2025
1,ORD1002,12-04-2025,Simran,simran33@gmail.com,9.031995e+09,Pune,Maharashtra,Mouse,Electronics,2.0,399.0,20.0,UPI,Delivered,22-04-2025
2,ORD1003,23-05-2025,Anjali,anjali460@gmail.com,9.632719e+09,Mumbai,Maharashtra,Chair,Furniture,2.0,2499.0,10.0,COD,Pending,30-05-2025
3,ORD1004,24-08-2025,Amit,amit390@gmail.com,9.103848e+09,Lucknow,Uttar Pradesh,Bottle,Home,5.0,799.0,0.0,COD,Delivered,01-09-2025
4,ORD1005,24-01-2025,Shreya,shreya301@gmail.com,9.890566e+09,Surat,Gujarat,Smartphone,Electronics,3.0,17999.0,0.0,COD,Delivered,30-01-2025

In [11]:
# Step 4: Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       50000 non-null  object
 1   Order_Date     50000 non-null  object
 2   Customer_Name  50000 non-null  object
 3   Email          50000 non-null  object
 4   Phone          49501 non-null  float64
 5   City           50000 non-null  object
 6   State          50000 non-null  object
 7   Product        50000 non-null  object
 8   Category       50000 non-null  object
 9   Qty            49743 non-null  float64
 10  Unit_Price     49002 non-null  float64
 11  Discount       49000 non-null  float64
 12  Payment_Mode   50000 non-null  object
 13  Order_Status   50000 non-null  object
 14  Delivery_Date  44368 non-null  object
dtypes: float64(4), object(11)
memory usage: 5.7+ MB

In [12]:
# Statistical Summary
df.describe()

              Phone           Qty    Unit_Price      Discount
count  4.950100e+04  49743.000000  49002.000000  49000.000000
mean   9.500101e+09      2.951631   9083.788376     10.020408
std    2.888761e+08      1.476850  16346.253869      7.055869
min    9.000036e+09     -2.000000    299.000000      0.000000
25%    9.249556e+09      2.000000    999.000000      5.000000
50%    9.500694e+09      3.000000   2499.000000     10.000000
75%    9.750444e+09      4.000000   7999.000000     15.000000
max    9.999996e+09      5.000000  74999.000000     20.000000

In [13]:
# Dataset Shape

df.shape

(50000, 15)

In [14]:
# Step 4: check Missing Values

df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Email               0
Phone             499
City                0
State               0
Product             0
Category            0
Qty               257
Unit_Price        998
Discount         1000
Payment_Mode        0
Order_Status        0
Delivery_Date    5632
dtype: int64

In [15]:
# Step 5: Check Duplicate Records

df.duplicated().sum()

np.int64(100)

In [16]:
# Remove Duplicate Records

df.drop_duplicates(inplace=True)

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
# Step 6: Replace Invalid Values
# Replace common invalid values with NaN

df.replace(['N/A','NULL',''],np.nan,inplace=True)

In [19]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1001,13-12-2025,Vikas,vikas26@gmail.com,9.796234e+09,Mumbai,Maharashtra,Mouse,Electronics,2.0,499.0,0.0,COD,Delivered,23-12-2025
1,ORD1002,12-04-2025,Simran,simran33@gmail.com,9.031995e+09,Pune,Maharashtra,Mouse,Electronics,2.0,399.0,20.0,UPI,Delivered,22-04-2025
2,ORD1003,23-05-2025,Anjali,anjali460@gmail.com,9.632719e+09,Mumbai,Maharashtra,Chair,Furniture,2.0,2499.0,10.0,COD,Pending,30-05-2025
3,ORD1004,24-08-2025,Amit,amit390@gmail.com,9.103848e+09,Lucknow,Uttar Pradesh,Bottle,Home,5.0,799.0,0.0,COD,Delivered,01-09-2025
4,ORD1005,24-01-2025,Shreya,shreya301@gmail.com,9.890566e+09,Surat,Gujarat,Smartphone,Electronics,3.0,17999.0,0.0,COD,Delivered,30-01-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49895,ORD50896,25-11-2025,Manish,manish793@gmail.com,9.081181e+09,Indore,Madhya Pradesh,Office Desk,Furniture,5.0,NaN,10.0,UPI,Delivered,29-11-2025
49896,ORD50897,11-04-2025,Priya,priya206@gmail.com,9.626696e+09,Delhi,Delhi,Office Desk,Furniture,3.0,9999.0,5.0,NetBanking,Delivered,22-04-2025
49897,ORD50898,25-05-2025,Riya,riya239@gmail.com,9.247881e+09,Kolkata,West Bengal,Shoes,Fashion,4.0,1499.0,5.0,COD,Delivered,06-06-2025
49898,ORD50899,25-12-2025,Riya,riya978@gmail.com,9.947154e+09,Noida,Uttar Pradesh,Bottle,Home,4.0,999.0,15.0,Card,Delivered,31-12-2025
49899,ORD50900,05-07-2025,Amit,amit590@gmail.com,9.695736e+09,Bengaluru,Karnataka,Watch,Fashion,1.0,2999.0,5.0,Wallet,Pending,07-07-2025

In [20]:
# Step 7: Remove Extra Spaces

df = df.apply(lambda x: x.str.strip() if x.dtype =='object' else x)

In [21]:
# Step 8: Standardize Text Format
# Convert text into Proper Case.

df['Customer_Name'] = df['Customer_Name'].str.title()

df['City'] = df['City'].str.title()

df['State'] = df['State'].str.title()

In [22]:
# Step 9: Validate Email records
# Keep only valid Email records.

df = df[df['Email'].str.contains('@',na=False)]

In [23]:
# Step 10 Convert Date Columns

df['Order_Date'] = pd.to_datetime(
    df['Order_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)

df['Delivery_Date'] = pd.to_datetime(
    df['Delivery_Date'],
    format='%d-%m-%Y',
    errors='coerce'
)

In [24]:
# Step 11: Convert Numeric Columns

cols = ['Qty','Unit_Price','Discount']

for c in cols:
    df[c] = pd.to_numeric(df[c],errors='coerce')

In [25]:
# Step 12: Remove Invalid Quantity
# Remove records having negative or zero quantity.

df = df[df['Qty']>0]

In [26]:
# Step 13: Fill Missing Values

df['Discount'] = df['Discount'].fillna(0)

df['Phone'] = df['Phone'].fillna('Unknown')

df['Delivery_Date'] = df['Delivery_Date'].fillna(df['Order_Date'])

# Featuer Engineering

In [27]:
# Total Sales

df['Sales']=df['Qty']*df['Unit_Price']

In [28]:
# Net Amount

df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [29]:
df

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount
0,ORD1001,2025-12-13,Vikas,vikas26@gmail.com,9796233790.0,Mumbai,Maharashtra,Mouse,Electronics,2.0,499.0,0.0,COD,Delivered,2025-12-23,998.0,998.00
1,ORD1002,2025-04-12,Simran,simran33@gmail.com,9031994523.0,Pune,Maharashtra,Mouse,Electronics,2.0,399.0,20.0,UPI,Delivered,2025-04-22,798.0,638.40
2,ORD1003,2025-05-23,Anjali,anjali460@gmail.com,9632719211.0,Mumbai,Maharashtra,Chair,Furniture,2.0,2499.0,10.0,COD,Pending,2025-05-30,4998.0,4498.20
3,ORD1004,2025-08-24,Amit,amit390@gmail.com,9103848421.0,Lucknow,Uttar Pradesh,Bottle,Home,5.0,799.0,0.0,COD,Delivered,2025-09-01,3995.0,3995.00
4,ORD1005,2025-01-24,Shreya,shreya301@gmail.com,9890566476.0,Surat,Gujarat,Smartphone,Electronics,3.0,17999.0,0.0,COD,Delivered,2025-01-30,53997.0,53997.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49895,ORD50896,2025-11-25,Manish,manish793@gmail.com,9081181131.0,Indore,Madhya Pradesh,Office Desk,Furniture,5.0,NaN,10.0,UPI,Delivered,2025-11-29,NaN,NaN
49896,ORD50897,2025-04-11,Priya,priya206@gmail.com,9626695552.0,Delhi,Delhi,Office Desk,Furniture,3.0,9999.0,5.0,NetBanking,Delivered,2025-04-22,29997.0,28497.15
49897,ORD50898,2025-05-25,Riya,riya239@gmail.com,9247881157.0,Kolkata,West Bengal,Shoes,Fashion,4.0,1499.0,5.0,COD,Delivered,2025-06-06,5996.0,5696.20
49898,ORD50899,2025-12-25,Riya,riya978@gmail.com,9947153603.0,Noida,Uttar Pradesh,Bottle,Home,4.0,999.0,15.0,Card,Delivered,2025-12-31,3996.0,3396.60
49899,ORD50900,2025-07-05,Amit,amit590@gmail.com,9695736147.0,Bengaluru,Karnataka,Watch,Fashion,1.0,2999.0,5.0,Wallet,Pending,2025-07-07,2999.0,2849.05

In [30]:
# Profit(Example)
df['Profit']=df['Net_Amount']*0.20

In [32]:
# Order Month

df['Month']=df['Order_Date'].dt.month_name()

In [34]:
# Order Year

df["Year"]=df['Order_Date'].dt.year

In [36]:
# Weekday

df["Weekday"]=df['Order_Date'].dt.day_name()

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49152 entries, 0 to 49899
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       49152 non-null  object
 1   Order_Date     48666 non-null  datetime64[ns]
 2   Customer_Name  49152 non-null  object
 3   Email          49152 non-null  object
 4   Phone          49152 non-null  object
 5   City           49152 non-null  object
 6   State          49152 non-null  object
 7   Product        49152 non-null  object
 8   Category       49152 non-null  object
 9   Qty            49152 non-null  float64
 10  Unit_Price     48169 non-null  float64
 11  Discount       49152 non-null  float64
 12  Payment_Mode   49152 non-null  object
 13  Order_Status   49152 non-null  object
 14  Delivery_Date  49096 non-null  datetime64[ns]
 15  Sales          48169 non-null  float64
 16  Net_Amount     48169 non-null  float64
 17  Profit         48169 non-null  float64
 18  Month          48666 non-null  object
 19  Year           48666 non-null  float64
 20  Weekday        48666 non-null  object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 8.2+ MB

In [39]:
df.isnull().sum()

Order_ID           0
Order_Date       486
Customer_Name      0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Qty                0
Unit_Price       983
Discount           0
Payment_Mode       0
Order_Status       0
Delivery_Date     56
Sales            983
Net_Amount       983
Profit           983
Month            486
Year             486
Weekday          486
dtype: int64

df.describe()

In [40]:
# Step 16: Export Clean Data
df.to_csv('Clean_Ecommerce.csv',index=False)

# Import Data Postger SQl.

In [52]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    port=5432,
    database="E-Commerce",
    user="postgres",
    password="Your_password"
)

print("Connection successful!")

Connection successful!

In [56]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = "Your_password"

engine = create_engine(
    f"postgresql+psycopg2://postgres:{quote_plus(password)}@localhost:5432/E-Commerce"
)

print("Connection successful!")

Connection successful!

In [57]:
df.to_sql(
    "ecommerce_orders",
    engine,
    if_exists="replace",
    index=False
)

print("Data imported successfully!")

Data imported successfully!

In [58]:
query = "SELECT * FROM ecommerce_orders LIMIT 10"

data = pd.read_sql(query, engine)

data

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,Net_Amount,Profit,Month,Year,Weekday
0,ORD1001,2025-12-13,Vikas,vikas26@gmail.com,9796233790.0,Mumbai,Maharashtra,Mouse,Electronics,2.0,...,0.0,COD,Delivered,2025-12-23,998.0,998.0,199.60,December,2025.0,Saturday
1,ORD1002,2025-04-12,Simran,simran33@gmail.com,9031994523.0,Pune,Maharashtra,Mouse,Electronics,2.0,...,20.0,UPI,Delivered,2025-04-22,798.0,638.4,127.68,April,2025.0,Saturday
2,ORD1003,2025-05-23,Anjali,anjali460@gmail.com,9632719211.0,Mumbai,Maharashtra,Chair,Furniture,2.0,...,10.0,COD,Pending,2025-05-30,4998.0,4498.2,899.64,May,2025.0,Friday
3,ORD1004,2025-08-24,Amit,amit390@gmail.com,9103848421.0,Lucknow,Uttar Pradesh,Bottle,Home,5.0,...,0.0,COD,Delivered,2025-09-01,3995.0,3995.0,799.00,August,2025.0,Sunday
4,ORD1005,2025-01-24,Shreya,shreya301@gmail.com,9890566476.0,Surat,Gujarat,Smartphone,Electronics,3.0,...,0.0,COD,Delivered,2025-01-30,53997.0,53997.0,10799.40,January,2025.0,Friday
5,ORD1006,2025-07-09,Anjali,anjali888@gmail.com,9108449460.0,Hyderabad,Telangana,Laptop,Electronics,4.0,...,5.0,Wallet,Delivered,2025-07-21,239996.0,227996.2,45599.24,July,2025.0,Wednesday
6,ORD1007,2025-07-14,Amit,amit624@gmail.com,9681802744.0,Jaipur,Rajasthan,Table,Furniture,2.0,...,15.0,NetBanking,Delivered,2025-07-26,7998.0,6798.3,1359.66,July,2025.0,Monday
7,ORD1008,2025-07-25,Anjali,anjali702@gmail.com,9348195935.0,Gurugram,Haryana,Chair,Furniture,2.0,...,10.0,NetBanking,Delivered,2025-07-30,1998.0,1798.2,359.64,July,2025.0,Friday
8,ORD1009,2025-03-13,Karan,karan218@gmail.com,9703771909.0,Chennai,Tamil Nadu,Headphones,Electronics,4.0,...,10.0,NetBanking,Pending,2025-03-23,5996.0,5396.4,1079.28,March,2025.0,Thursday
9,ORD1010,2025-03-12,Arjun,arjun765@gmail.com,9627694430.0,Hyderabad,Telangana,Smartphone,Electronics,4.0,...,5.0,COD,Delivered,2025-03-15,99996.0,94996.2,18999.24,March,2025.0,Wednesday

In [59]:
query = "SELECT COUNT(*) AS total_rows FROM ecommerce_orders"

pd.read_sql(query, engine)

   total_rows
0       49152

In [60]:
data.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Email', 'Phone', 'City',
       'State', 'Product', 'Category', 'Qty', 'Unit_Price', 'Discount',
       'Payment_Mode', 'Order_Status', 'Delivery_Date', 'Sales', 'Net_Amount',
       'Profit', 'Month', 'Year', 'Weekday'],
      dtype='object')